import { useState } from "react";
import { Link } from "wouter";
import { BookOpen, CalendarPlus, CheckCircle2, Pause, Plus, Target, Trash2, Users } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { Badge } from "@workspace/edu-ds/components/ui/badge";
import { Button } from "@workspace/edu-ds/components/ui/button";
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@workspace/edu-ds/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@workspace/edu-ds/components/ui/dialog";
import { Input } from "@workspace/edu-ds/components/ui/input";
import { Label } from "@workspace/edu-ds/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@workspace/edu-ds/components/ui/select";
import { Skeleton } from "@workspace/edu-ds/components/ui/skeleton";
import { Textarea } from "@workspace/edu-ds/components/ui/textarea";
import { toast } from "@workspace/edu-ds/hooks/use-toast";
import { getListLearningGoalsQueryKey, LearningGoalInputLevel, LearningGoalStatus, useCreateLearningGoal, useDeleteLearningGoal, useListLearningGoals, useUpdateLearningGoal } from "@workspace/api-client-react";

export default function GoalsPage() {
 const client = useQueryClient();
 const { data: goals, isLoading } = useListLearningGoals({ query: { queryKey: getListLearningGoalsQueryKey() } });
 const createGoal = useCreateLearningGoal(), updateGoal = useUpdateLearningGoal(), deleteGoal = useDeleteLearningGoal();
 const [open, setOpen] = useState(false);
 const [form, setForm] = useState({ title: "", subject: "", description: "", level: LearningGoalInputLevel.beginner, targetDate: "" });
 async function refresh() { await client.invalidateQueries({ queryKey: getListLearningGoalsQueryKey() }); }
 async function submit(event: React.FormEvent) { event.preventDefault(); try { await createGoal.mutateAsync({ data: { title: form.title.trim(), subject: form.subject.trim(), description: form.description.trim() || null, level: form.level, targetDate: form.targetDate || null, preferredFormats: [] } }); await refresh(); setOpen(false); setForm({ title: "", subject: "", description: "", level: LearningGoalInputLevel.beginner, targetDate: "" }); toast({ title: "Learning goal created", description: "Your next steps are ready." }); } catch { toast({ title: "Could not create goal", variant: "destructive" }); } }
 async function changeStatus(id: number, status: typeof LearningGoalStatus[keyof typeof LearningGoalStatus]) { await updateGoal.mutateAsync({ id, data: { status } }); await refresh(); }
 async function remove(id: number) { if (!confirm("Delete this learning goal?")) return; await deleteGoal.mutateAsync({ id }); await refresh(); }
 return <div className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6 lg:p-8">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><Target className="size-6 text-primary" />Learning goals</h1><p className="mt-1 text-sm text-muted-foreground">Turn an outcome into trusted resources, useful people and scheduled action.</p></div>
   <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus className="mr-2 size-4" />New goal</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create a learning goal</DialogTitle><DialogDescription>Be specific about the outcome you want, not just the subject.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><div><Label htmlFor="goal-title">Outcome</Label><Input id="goal-title" value={form.title} onChange={(e) => setForm((old) => ({ ...old, title: e.target.value }))} placeholder="Understand quadratic equations" minLength={2} maxLength={160} required /></div><div><Label htmlFor="goal-subject">Subject</Label><Input id="goal-subject" value={form.subject} onChange={(e) => setForm((old) => ({ ...old, subject: e.target.value }))} placeholder="Mathematics" required /></div><div><Label>Current level</Label><Select value={form.level} onValueChange={(level) => setForm((old) => ({ ...old, level: level as typeof form.level }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value={LearningGoalInputLevel.beginner}>Beginner</SelectItem><SelectItem value={LearningGoalInputLevel.intermediate}>Intermediate</SelectItem><SelectItem value={LearningGoalInputLevel.advanced}>Advanced</SelectItem></SelectContent></Select></div><div><Label htmlFor="goal-date">Target date <span className="text-muted-foreground">(optional)</span></Label><Input id="goal-date" type="date" value={form.targetDate} onChange={(e) => setForm((old) => ({ ...old, targetDate: e.target.value }))} /></div><div><Label htmlFor="goal-description">Context <span className="text-muted-foreground">(optional)</span></Label><Textarea id="goal-description" value={form.description} onChange={(e) => setForm((old) => ({ ...old, description: e.target.value }))} placeholder="What success looks like, what you already know, or what is difficult…" maxLength={1000} /></div><DialogFooter><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" disabled={createGoal.isPending}>Create goal</Button></DialogFooter></form></DialogContent></Dialog>
  </div>
  {isLoading ? <div className="grid gap-4 md:grid-cols-2">{[1,2,3,4].map((item) => <Skeleton key={item} className="h-72 rounded-xl" />)}</div> : !goals?.length ? <div className="rounded-xl border border-dashed py-16 text-center"><Target className="mx-auto mb-3 size-10 text-muted-foreground/40" /><p className="font-semibold">Create your first learning goal</p><p className="mt-1 text-sm text-muted-foreground">Schoolar will connect it to resources, people and time.</p></div> : <div className="grid gap-4 md:grid-cols-2">{goals.map((goal) => { const query = encodeURIComponent(goal.title), subject = encodeURIComponent(goal.subject); return <Card key={goal.id} className={goal.status === LearningGoalStatus.completed ? "opacity-70" : ""}><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-lg">{goal.title}</CardTitle><div className="mt-2 flex flex-wrap gap-2"><Badge variant="secondary">{goal.subject}</Badge><Badge variant="outline" className="capitalize">{goal.level}</Badge><Badge className="capitalize">{goal.status}</Badge></div></div><Button variant="ghost" size="sm" onClick={() => remove(goal.id)} aria-label="Delete goal"><Trash2 className="size-4" /></Button></div></CardHeader><CardContent className="space-y-4">{goal.description && <p className="text-sm text-muted-foreground">{goal.description}</p>}{goal.targetDate && <p className="text-xs text-muted-foreground">Target: {new Date(`${goal.targetDate}T00:00:00`).toLocaleDateString()}</p>}<div className="grid grid-cols-1 gap-2 sm:grid-cols-3"><Button variant="outline" size="sm" asChild><Link href={`/resources?goal=${query}&subject=${subject}`}><BookOpen className="mr-2 size-4" />Resources</Link></Button><Button variant="outline" size="sm" asChild><Link href={`/people?goal=${query}&subject=${subject}`}><Users className="mr-2 size-4" />People</Link></Button><Button variant="outline" size="sm" asChild><Link href={`/schedule?goal=${query}`}><CalendarPlus className="mr-2 size-4" />Schedule</Link></Button></div></CardContent><CardFooter className="justify-end">{goal.status === LearningGoalStatus.completed ? <Button size="sm" variant="outline" onClick={() => changeStatus(goal.id, LearningGoalStatus.active)}>Reopen</Button> : <><Button size="sm" variant="ghost" onClick={() => changeStatus(goal.id, goal.status === LearningGoalStatus.paused ? LearningGoalStatus.active : LearningGoalStatus.paused)}><Pause className="mr-2 size-4" />{goal.status === LearningGoalStatus.paused ? "Resume" : "Pause"}</Button><Button size="sm" onClick={() => changeStatus(goal.id, LearningGoalStatus.completed)}><CheckCircle2 className="mr-2 size-4" />Complete</Button></>}</CardFooter></Card>; })}</div>}
 </div>;
}
