CREATE INDEX IF NOT EXISTS "activity_log_user_id_idx" ON "activity_log" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "assignment_completions_user_id_idx" ON "assignment_completions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "canvas_collaborators_added_by_id_idx" ON "canvas_collaborators" USING btree ("added_by_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "class_assignments_activity_id_idx" ON "class_assignments" USING btree ("activity_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "class_assignments_created_by_id_idx" ON "class_assignments" USING btree ("created_by_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "class_assignments_resource_id_idx" ON "class_assignments" USING btree ("resource_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "class_invitations_invited_by_id_idx" ON "class_invitations" USING btree ("invited_by_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "class_members_class_id_idx" ON "class_members" USING btree ("class_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "class_resource_recommendations_recommended_by_id_idx" ON "class_resource_recommendations" USING btree ("recommended_by_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "class_resource_recommendations_resource_id_idx" ON "class_resource_recommendations" USING btree ("resource_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "class_resource_recommendations_reviewed_by_id_idx" ON "class_resource_recommendations" USING btree ("reviewed_by_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "classes_teacher_id_idx" ON "classes" USING btree ("teacher_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "direct_conversations_requested_by_id_idx" ON "direct_conversations" USING btree ("requested_by_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "direct_messages_sender_id_idx" ON "direct_messages" USING btree ("sender_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "forum_comments_author_id_idx" ON "forum_comments" USING btree ("author_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "forum_material_approvals_teacher_id_idx" ON "forum_material_approvals" USING btree ("teacher_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "forum_materials_uploader_id_idx" ON "forum_materials" USING btree ("uploader_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "forum_posts_attachment_material_id_idx" ON "forum_posts" USING btree ("attachment_material_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "forum_posts_author_id_idx" ON "forum_posts" USING btree ("author_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "forum_reports_reporter_id_idx" ON "forum_reports" USING btree ("reporter_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "forum_survey_votes_user_id_idx" ON "forum_survey_votes" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "learning_evidence_learning_goal_id_idx" ON "learning_evidence" USING btree ("learning_goal_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "learning_evidence_resource_id_idx" ON "learning_evidence" USING btree ("resource_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "learning_evidence_user_id_idx" ON "learning_evidence" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "learning_goals_user_id_idx" ON "learning_goals" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "list_items_list_id_idx" ON "list_items" USING btree ("list_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "list_items_resource_id_idx" ON "list_items" USING btree ("resource_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "resource_lists_class_id_idx" ON "resource_lists" USING btree ("class_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "resource_lists_owner_id_idx" ON "resource_lists" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "resources_submitted_by_id_idx" ON "resources" USING btree ("submitted_by_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "reviews_user_id_idx" ON "reviews" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "schedule_blocks_class_id_idx" ON "schedule_blocks" USING btree ("class_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "schedule_blocks_list_id_idx" ON "schedule_blocks" USING btree ("list_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "schedule_blocks_resource_id_idx" ON "schedule_blocks" USING btree ("resource_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "schedule_blocks_user_id_idx" ON "schedule_blocks" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "study_session_participants_user_id_idx" ON "study_session_participants" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "study_sessions_organizer_id_idx" ON "study_sessions" USING btree ("organizer_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "study_sessions_resource_id_idx" ON "study_sessions" USING btree ("resource_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_blocks_blocked_id_idx" ON "user_blocks" USING btree ("blocked_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_reports_reported_id_idx" ON "user_reports" USING btree ("reported_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_reports_reporter_id_idx" ON "user_reports" USING btree ("reporter_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "workflow_events_assignment_id_idx" ON "workflow_events" USING btree ("assignment_id");
